name: Build ATTOX

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            mtools \
            nasm 

      - name: Build OS image x86
        run: |
          make clean || true
          make

      - name: Upload OS image x86
        uses: actions/upload-artifact@v4
        with:
          name: os-image-x86
          path: os-image.img
